#!/bin/bash
#
# Title:      PGBlitz.com (Reference Title File)
# Author(s):  Admin9705
# URL:        https://pgblitz.com - http://github.pgblitz.com
# GNU:        General Public License v3.0
################################################################################
sudo nano /opt/appdata/plexguide/pgblitz.sh && sudo systemctl restart pgblitz
