#!/bin/bash
#
# Title:      PGBlitz.com (Reference Title File)
# Author(s):  Admin9705
# URL:        https://pgblitz.com - http://github.pgblitz.com
# GNU:        General Public License v3.0
################################################################################
nano /pg/data/blitz/pgblitz.sh && systemctl daemon-reload
