#!/bin/bash
#
# [Ansible Role]
#
# GitHub:     https://github.com/PGBlitz/PGBlitz.com
# Maintainer: Admin9705 & Deiteq
# URL:        https://pgblitz.com
#
# PlexGuide Copyright (C) 2018 PlexGuide.com
# Licensed under GNU General Public License v3.0 GPL-3 (in short)
#
#   You may copy, distribute and modify the software as long as you track
#   changes/dates in source files. Any modifications to our software
#   including (via compiler) GPL-licensed code must also be made available
#   under the GPL along with build & install instructions.
#
#################################################################################
sudo systemctl status pgblitz
